// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)


bool house1;
bool house2;
bool middle;
bool north;
bool south;

void initProperties(){

  ArduinoCloud.addProperty(house1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(house2, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(middle, READ, ON_CHANGE, NULL, 1);
  ArduinoCloud.addProperty(north, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(south, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
